### ISSUE TITLE
Headless() Problem

### ISSUE THREAD

**Issue by crowmatix** [PNeumann99/wg_updater#3]
TypeError: (intermediate value).headless is not a function
    at update_offer (/home/ ___ /wg_updater/wg_updater.js:12:44)
    at Object.<anonymous> (/home/ ___ /wg_updater/wg_updater.js:62:1)

Solution: 

let options = new chrome.Options();
options.addArguments("--headless");
options.addArguments("--window-size=640,480");

let driver = new Builder()
    .forBrowser("chrome")
    .setChromeOptions(options)
    .build();

_________________________________

But then I get 

![grafik](https://github.com/PNeumann99/wg_updater/assets/91941203/17b1bdb7-31ec-4ec5-a777-504fd85ff0a6)

Any idea?

**Comment by PNeumann99** [comment]
So i pushed a fix for the issue with the deprecated headless option of selenium and it is working for me. 

You could try commenting out the headless part in the (new) code and see if wg-gesucht made some changes to the website that break the automation script. It should open the offering on the edit page.
